require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MaestrosController do

  # This should return the minimal set of attributes required to create a valid
  # Maestro. As you add validations to Maestro, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MaestrosController. Be sure to keep this updated too.
  def valid_session
    {}
  end



 
  describe "GET new" do
    it "assigns a new maestro as @maestro" do
      get :new, {}, valid_session
      assigns(:maestro).should be_a_new(Maestro)
    end
  end



  describe "POST create" do
    describe "with valid params" do
      it "creates a new Maestro" do
        expect {
          post :create, {:maestro => valid_attributes}, valid_session
        }.to change(Maestro, :count).by(1)
      end

      it "assigns a newly created maestro as @maestro" do
        post :create, {:maestro => valid_attributes}, valid_session
        assigns(:maestro).should be_a(Maestro)
        assigns(:maestro).should be_persisted
      end

      it "redirects to the created maestro" do
        post :create, {:maestro => valid_attributes}, valid_session
        response.should redirect_to(Maestro.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved maestro as @maestro" do
        # Trigger the behavior that occurs when invalid params are submitted
        Maestro.any_instance.stub(:save).and_return(false)
        post :create, {:maestro => {}}, valid_session
        assigns(:maestro).should be_a_new(Maestro)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Maestro.any_instance.stub(:save).and_return(false)
        post :create, {:maestro => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested maestro" do
        maestro = Maestro.create! valid_attributes
        # Assuming there are no other maestros in the database, this
        # specifies that the Maestro created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Maestro.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => maestro.to_param, :maestro => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested maestro as @maestro" do
        maestro = Maestro.create! valid_attributes
        put :update, {:id => maestro.to_param, :maestro => valid_attributes}, valid_session
        assigns(:maestro).should eq(maestro)
      end

      it "redirects to the maestro" do
        maestro = Maestro.create! valid_attributes
        put :update, {:id => maestro.to_param, :maestro => valid_attributes}, valid_session
        response.should redirect_to(maestro)
      end
    end

    describe "with invalid params" do
      it "assigns the maestro as @maestro" do
        maestro = Maestro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Maestro.any_instance.stub(:save).and_return(false)
        put :update, {:id => maestro.to_param, :maestro => {}}, valid_session
        assigns(:maestro).should eq(maestro)
      end

      it "re-renders the 'edit' template" do
        maestro = Maestro.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Maestro.any_instance.stub(:save).and_return(false)
        put :update, {:id => maestro.to_param, :maestro => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested maestro" do
      maestro = Maestro.create! valid_attributes
      expect {
        delete :destroy, {:id => maestro.to_param}, valid_session
      }.to change(Maestro, :count).by(-1)
    end

    it "redirects to the maestros list" do
      maestro = Maestro.create! valid_attributes
      delete :destroy, {:id => maestro.to_param}, valid_session
      response.should redirect_to(maestros_url)
    end
  end

end
